#!/usr/bin/env python3
"""Deterministic Amharic (Ge'ez) string builder.

Why this exists: hand-typed Ethiopic script was observed to suffer glyph
dropping when generated by LLM tooling. This module compiles Amharic words
from romanised syllable specs into Unicode code points arithmetically, so the
output is exact by construction.

Spec format: space-separated tokens.
  token   = <consonant><vowel>   e.g. "mA" -> ማ , "yE" -> ይ , "TS" -> ጸ
  vowel   = A(ä,1st) u(2nd) i(3rd) a(4th) e(5th) E(ə,6th) o(7th)
  specials: "QA" -> ቔ ; literal chars: digits, "-", ",", ".", "(", ")", "/"
            "."  -> ። (ethiopic full stop)
Consonant keys (base = 1st-order code point):
  h ሀ, l ለ, m መ, r ረ, s ሰ, sh ሸ, q ቀ, b በ, t ተ, ch ጨ, n ነ, ny ኘ,
  a አ(alef), k ከ, w ወ, z ዘ, y የ, d ደ, j ጀ, g ገ, T ጠ(ejective t),
  TS ጸ(ejective ts), f ፈ, p ፐ
"""

BASE = {
    "h": 0x1200, "l": 0x1208, "m": 0x1218, "r": 0x1228, "s": 0x1230,
    "sh": 0x1238, "q": 0x1240, "b": 0x1260, "t": 0x1270, "CH": 0x1278, "ch": 0x1328,
    "n": 0x1290, "ny": 0x1298, "a": 0x12A0, "k": 0x12A8, "w": 0x12C8,
    "z": 0x12D8, "y": 0x12E8, "d": 0x12F0, "j": 0x1300, "g": 0x1308, "a2": 0x12D0, "H": 0x1210,
    "HH": 0x1280,   # ኀ-series (ርኅራኄ)
    "HW": 0x1288,   # ኈ-labialized (ኋ in በኋላ)
    "kW": 0x12B0,   # ኰ-labialized (ቋ in ቋንቋ/ቋሚ/እንኳን) "kW": 0x12B0,
    "T": 0x1320, "TS": 0x1338, "TP": 0x1330, "SA": 0x1220, "f": 0x1348, "p": 0x1350,
}
VOWEL = {"A": 0, "u": 1, "i": 2, "a": 3, "e": 4, "E": 5, "o": 6, "W": 7}  # W = labialized 7th (ሷ ጷ ሏ)
SPECIAL = {"QA": 0x1254}  # ቔ
CONSONANTS = sorted(BASE, key=len, reverse=True)  # longest-first: sh, ny, ch, TS, a2 …


def syl(token: str) -> str:
    if token in SPECIAL:
        return chr(SPECIAL[token])
    if token in BASE:               # bare consonant -> 1st order
        return chr(BASE[token])
    for c in CONSONANTS:
        if token.startswith(c) and len(token) == len(c) + 1:
            v = token[len(c)]
            if v in ("U", "I", "O"):
                v = v.lower()
            if v in VOWEL:
                return chr(BASE[c] + VOWEL[v])
    raise ValueError(f"bad syllable token: {token!r}")


PUNCT = set("+-()/.,\u2014\u2026\u00b7?!'\":;\u2713\u2019\u2018\u201c\u201d\u1366\u1361\u1362\u1363\u1364\u1365")


def am(spec: str) -> str:
    out = []
    for token in spec.split(" "):
        if token == "~":
            out.append(" ")
        elif token.isdigit():
            out.append(token)
        elif token.startswith("{") and token.endswith("}"):
            out.append(token)  # {placeholder} — interpolated at runtime
        elif token and all(ch in PUNCT or ch.isdigit() for ch in token):
            out.append("\u1362" if token == "." else token)
        else:
            try:
                out.append(syl(token))
            except ValueError:
                if token.isascii() and any(c.isalpha() for c in token):
                    out.append(token)  # brand/loan Latin words pass through
                else:
                    raise
    return "".join(out)


# ---------------------------------------------------------------- vocabulary
W = {
    # register / pronouns
    "erswo": "aE rE sE wO",
    "ersachew": "aE sa CHA wE",
    # core nouns
    "kidan": "ki da nE",
    "twwq": "tE wE wE qE",
    "tyaq": "TE ya qe",
    "tyaqw": "TE ya qe wE",
    "tyaqoch": "TE ya qe wO kE",
    "yetwwq": "yA tE wE wE qE",
    "gnyt": "gE nE nyU nA tE",
    "gnytoch": "gE nE nyU nA tO kE",
    "yegl": "yA gE lE",
    "gl": "gE lE",
    "glawinet": "gE la wI nA tE",
    "mrcha": "mE rE cha",
    "zrzr": "zE rE zE rE",
    "zrzro": "zE rE zE rE wO",
    "eset": "aE se tE",
    "beset": "bA aE se tE",
    "bcha": "bE CHa",
    "tekor": "tE kO rE",
    "mrgcha": "ma rA ga gE cha",
    "ymrgcha": "yA ma rA ga gE cha",
    "mrgchaw": "ma rA ga gE cha wE",
    "foto": "fO tO",
    "fotow": "fO tO wE",
    "ymnnet": "yA ma nE nA tE",
    "gmema": "gE mE gA ma",
    "gamagi": "gA ma gI",
    "astedari": "aA sE tA da da rI",
    "megelecha": "mA gA lA cha",
    "yemegelecha": "yA mA gA lA cha",
    "kod": "kO dE",
    "achr": "aA chE rE",
    "twway": "tA wa wa yE",
    "agaro": "aA ga rE wO",
    # journey
    "fleka": "fE lA ga",
    "asus": "aE sE sE",
    "magnet": "ma gA nyA tE",
    "wd": "wA dA",
    "qgn": "qA nyE",
    "yanshrttu": "ya nE shA ra tE tu",
    "manshratet": "ma nE shA ra tA tE",
    "yasgabu": "ya sE gA bu",
    "tlk": "tA la kA",
    "tqbl": "tA qA bA lA",
    "tmls": "tA mA lE sA",
    "tms": "tA mA lA sE",
    "yqblu": "yE qA bA lu",
    "yargtu": "ya rA ga gE TU",
    "bmTbbq_lay": "bA mA TA bA bA qE ~ la yE",
    "TSdq": "TS dE qE",
    "TSdqw": "TS dE qO",
    "wdq": "wE dE qE",
    "nggr": "nE gE gE rE",
    "mdrk": "mA dE rA kE",
    "yTSnd": "yA TE nE dE",
    "gzo": "gu zO",
    "qTayw": "qA TA yu",
    "ermja": "aE rE mE ja",
    "mkfet": "mA kA fE tE",
    "abr": "aA bE rO",
    "mgalet": "mA ga lA TE",
    "bakbro": "bA aA kE bE rO tE",
    "yzgu": "yE zE gu",
    "mzgat": "mA zE ga tE",
    "ers_bers_mtwwq": "aE rE sE ~ bA aE rE sE ~ mA tA wa wa qE",
    "zare": "za re",
    "symqrut": "yA mi qA ru tE",
    # privacy / safety
    "fqd": "fA qa dE",
    "glT": "gE lE TSE",
    "yfqd": "yA fA qa dE",
    "mzb": "mA zE gA bE",
    "ymgnya": "yA mA gA na nya",
    "mrja": "mA rA ja",
    "ywqya": "yA aE wE qE ya",
    "tklkll": "tA kA lA kA lA",
    "bfTum": "bA fE TSu mE",
    "aygram": "aA yE ga ra mE",
    "whb": "wE hI bE",
    "whbwo": "wE hI bE wO nE",
    "yawrdu": "ya wE rE du",
    "ysrzu": "yE sA rE zu",
    "mserz": "mA sA rA zE",
    "ytmstr": "yA tA mA sA TA rA",
    "mstr": "mA sA TA rA",
    "syalq": "si ya lE qE",
    "wst": "wE sE TE",
    "qnat": "HE yE wA tE",
    "ysrzal": "yE sA rA za lE",
    "manm": "ma nE mE",
    "aywqm": "aA ya wE qE mE",
    # actions / voice
    "yjmrw": "yE jA mE ru",
    "yqTlu": "yE qA TE lu",
    "lgmema": "lA gE mE gA ma",
    "yjbu": "yE gE bu",
    "gbtwal": "gA bE tA wa lE",
    "ywTu": "yE wE TU",
    "yasqmu": "ya sE qA mu TU",
    "endgna": "aE nE dA gA na",
    "ymkru": "yE mO kE ru",
    "hdton": "hI dA tE wO nE",
    "masqmet": "ma sE qA mE TE",
    "alchlnm": "aA lA CHa lE nE mE",
    "ebakwo": "aE ba kE wO",
    "slmta": "sA la mE ta",
    "mlkt": "mA lE aE kE tE",
    "ylku": "yE la ku",
    # community / faith
    "ortodoks": "aO rE tO dO kE sE",
    "twhdo": "tA wa HE dO",
    "krstyan": "kE rE sE tI ya nE",
    "emntna": "aE mE nA tE na",
    "btsb": "be tA sA bE",
    "sbkt": "sE bE kA tE",
    "gbI": "gE bI",
    "ybt": "yA be tA",
    "mhbrsb": "ma hE bA rA sA bE",
    "bealma": "bA aE se tE",
    "ymyalq": "yA ma ya lE qE",
    "aydlm": "aA yE dA lA mE",
    "pilot": "pi lO tE",
    "qdm_eyta": "qE dE mA - aE yE ta",
    "tegram": "te le gE ra mE",
    "profayl": "pE rO fa yI lE",
    "chat": "CHa tE",
    "amharnya": "aE ma rE nya",
}


def w(name: str) -> str:
    return am(W[name])


if __name__ == "__main__":
    import sys
    for k in sys.argv[1:]:
        print(k, "=", w(k))
